const TOKEN_TELEGRAM = import.meta.env.VITE_REACT_APP_TOKEN_TELEGRAM
const CHAT_ID_TELEGRAM = import.meta.env.VITE_REACT_APP_CHAT_ID_TELEGRAM

const GITHUB_API_URL = import.meta.env.VITE_REACT_APP_GITHUB_API_URL
const GITHUB_TOKEN = import.meta.env.VITE_REACT_APP_GITHUB_TOKEN

const GITREPOSITORY_OWNER=import.meta.env.VITE_REACT_APP_GITREPOSITORY_OWNER
const GITREPO=import.meta.env.VITE_REACT_APP_GITREPO
export {
   
    TOKEN_TELEGRAM,
    CHAT_ID_TELEGRAM,
    GITHUB_API_URL,
    GITHUB_TOKEN,
    GITREPOSITORY_OWNER,
    GITREPO
   
    
}